services:
  db:
    image: postgres:latest
    container_name: local_pgdb
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_DB: auth_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    image: tweeter/web
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - ./web/node_modules:/app/node_modules
  gateway:
    image: tweeter/gateway
    build: ./gateway
    ports:
      - "3001:4000"
      - "9228:9228" #debug port
    volumes:
      - ./gateway:/app
      - ./gateway/node_modules:/app/node_modules
      # - /app/node_modules
  authservice:
    image: tweeter/authservice
    build: ./authservice
    ports:
      - "3002:4000"
      - "9229:9229" #debug port
    volumes:
      - ./authservice:/app
      - ./authservice/node_modules:/app/node_modules
      # - /app/node_modules # this anonymous binding fixed the bcrypt error
volumes:
  db-data:
